### ISSUE TITLE
bbox polygon examples aren't linearrings

### ISSUE THREAD

**Issue by rclark** [geojson/geojson.github.io#16]
Hey @sgillies -- noticed today that on the specification page there are [examples of Polygons with `bbox` parameters](https://github.com/geojson/geojson.github.io/blob/1fe51d3c56f83c4e6601ac79be229e466ae9c83c/geojson-spec.md#4-bounding-boxes), but the coordinates are not LinearRings. Would here be the right place to change that?

**Comment by sgillies** [comment]
Thanks, @rclark!
