### ISSUE TITLE
Mark geojson spec as replaced by RFC 7946

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson.github.io#20]
@mpdaly points out that people can arrive at http://geojson.org/geojson-spec.html and not get a clue that RFC 7946 is the latest spec. I propose to add a "status: replaced by RFC 7946" entry to the table at the top of the spec page and leave the spec text untouched. Okay?

@tschaub @hobu @adoyle

**Comment by adoyle** [comment]
+1 from a small island in Maine...

--
