### ISSUE TITLE
Update geojson.org/geojson-spec.html ?

### ISSUE THREAD

**Issue by mapsam** [geojson/geojson.github.io#22]
Hello! Thank you for all your hard work on the GeoJSON spec and website. As someone who frequently refers to geojson.org for examples and specification-related details, I really enjoyed using the nicely laid out HTML page at http://geojson.org/geojson-spec.html. 

Ever since the most recent RFP release this page is now marked as "Obsolete" and links to the [official RFC](https://tools.ietf.org/html/rfc7946). The official page has the details but is lacking the accessibility similar to the previous spec page. Is there a plan to update geojson.org/geojson-spec.html at all? I'd be happy to lend a hand here, and know other folks who are interested as well.

Cheers!

cc @sgillies @tschaub @powersa @thedeb @foundatron

**Comment by tschaub** [comment]
I'm in favor of publishing the RFC 7946 spec at geojson.org (I find the formatting of ietf.org pages awkward and think there is room for improvement).

If we want to keep the old spec around, we could leave it at the current location and put the updated one at geojson.org/spec/ (adding a `spec/index.md` to https://github.com/geojson/geojson.github.io).

**Comment by mapsam** [comment]
Thanks @tschaub! Great idea. I've got some folks interested in helping out. We'll make a fork and work from there, planning to ask questions here. 

Happy to continue using the format from the previous spec page if that works for you. If we go with the `index.md` route there will need to be some sort of anchor logic for linking to headers within the page - I'll experiment.

**Comment by sgillies** [comment]
Sam, Tim, I'm :-1: on republishing RFC 7946 at geojson.org. There is
already an HTML version of the RFC at tools.ietf.org. It could potentially
be harmful to users as well. What if contradictory language crept in by
accident or design? Let's leave things as they are.

**Comment by tschaub** [comment]
I think it is worth addressing at least one problem:

https://www.google.com/search?q=geojson+spec
![image](https://cloud.githubusercontent.com/assets/41094/25066067/0226eb58-21d9-11e7-9ece-1eb6dcaee77e.png)

The first Google result for "geojson spec" leads to the "wrong" document.  [This doc](http://geojson.org/geojson-spec.html) is arguably more readable than the [IETF doc](https://tools.ietf.org/html/rfc7946).  And the "Obsolete" notice is too easy to overlook.  So I think it is wrong to do nothing - we're making it too easy for people to read the wrong doc.

I'll take this up separately, but at a minimum we should make it more obvious which document people should read.

**Comment by sgillies** [comment]
@tschaub I'm 👍 on making it more clear that http://geojson.org/geojson-spec.html is obsolete. Would it be useful to add a canonical link in http://geojson.org/geojson-spec.html to https://tools.ietf.org/html/rfc7946?

**Comment by tschaub** [comment]
#23 proposes more prominent links to RFC 7946 and discourages traffic to the obsolete spec.  I'm uncertain about `<link rel="canonical">` to a page with different content, so I've left that out.

**Comment by mapsam** [comment]
@sgillies totally fair. A more prominent notice that the leading google result is obsolete sounds 👍 to me. Thanks to you both!
