### ISSUE TITLE
github.com cert is not valid for geojson.org domain

### ISSUE THREAD

**Issue by sgillies** [geojson/geojson.github.io#24]
![untitled](https://user-images.githubusercontent.com/33697/26982493-e0ff5fce-4d38-11e7-9bcd-dfa71b837f3b.png)

**Comment by ekansa** [comment]
I don't know how to resolve this sort of thing. Maybe some documentation here: https://letsencrypt.org/

**Comment by coliff** [comment]
GitHub Pages support HTTPS for custom domains now. Info here:
https://github.blog/2018-05-01-github-pages-custom-domains-https/

**Comment by sgillies** [comment]
Yes @coliff, the missing piece is HTTPs configuration on the real geojson.org server. @mpdaly is the admin. It should be updated because browsers are going to cut geojson.org off entirely at some point in time.

**Comment by tschaub** [comment]
https://geojson.org/ is working now.
