### ISSUE TITLE
Syntax highlighter has marked colons as "errors" on live site

### ISSUE THREAD

**Issue by Hoolean** [geojson/geojson.github.io#25]
[See here](https://web.archive.org/web/20170830170028/http://geojson.org/) :(

Couldn't reproduce behaviour locally.

**Comment by Hoolean** [comment]
[Looks relevant](https://github.com/jekyll/jekyll/issues/6191#issuecomment-326789413)

**Comment by sgillies** [comment]
Thanks @Hoolean. Do keep in mind that this isn't the current GeoJSON specification since RFC 7946 was published.
